title:    "Rioki's Corner"
url:      http://gerhardm.github.io/ASHI/
baseurl:  http://gerhardm.github.io/ASHI
author:   Sean Farrell
email:    sean.farrell@rioki.org
markdown: kramdown
lsi:      false
pygments: true
future:   false
exclude:  [Gemfile, Gemfile.lock, wercker.yml]
